In [1]:
#Basic packages always been used
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# Data preprocessing useful function
from sklearn.preprocessing import LabelEncoder
# Function for spilting training & testing data set
from sklearn.model_selection import train_test_split
# ALgorithm
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
# Functions for evaluation
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import make_scorer
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import plot_roc_curve, roc_auc_score, roc_curve

In [2]:
df = pd.read_csv("heart.csv")

In [3]:
new_df=df.dropna(axis=0, how='any').copy()
new_df.describe(include='all')

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
count,918.000000,918,918,918.000000,918.000000,918.000000,918,918.000000,918,918.000000,918,918.000000
unique,NaN,2,4,NaN,NaN,NaN,3,NaN,2,NaN,3,NaN
top,NaN,M,ASY,NaN,NaN,NaN,Normal,NaN,N,NaN,Flat,NaN
freq,NaN,725,496,NaN,NaN,NaN,552,NaN,547,NaN,460,NaN
mean,53.510893,NaN,NaN,132.540305,240.581699,0.233115,NaN,136.809368,NaN,0.887364,NaN,0.553377
std,9.432617,NaN,NaN,17.989941,53.982967,0.423046,NaN,25.460334,NaN,1.066570,NaN,0.497414
min,28.000000,NaN,NaN,80.000000,85.000000,0.000000,NaN,60.000000,NaN,-2.600000,NaN,0.000000
25%,47.000000,NaN,NaN,120.000000,214.000000,0.000000,NaN,120.000000,NaN,0.000000,NaN,0.000000
50%,54.000000,NaN,NaN,130.000000,223.000000,0.000000,NaN,138.000000,NaN,0.600000,NaN,1.000000
75%,60.000000,NaN,NaN,140.000000,267.000000,0.000000,NaN,156.000000,NaN,1.500000,NaN,1.000000
max,77.000000,NaN,NaN,200.000000,603.000000,1.000000,NaN,202.000000,NaN,6.200000,NaN,1.000000

In [4]:
print('Age',new_df['Age'].unique())
print('Sex',new_df['Sex'].unique())
print('ChestPainType',new_df['ChestPainType'].unique())
print('RestingBP',new_df['RestingBP'].unique())
print('Cholesterol',new_df['Cholesterol'].unique())
print('FastingBS',new_df['FastingBS'].unique())
print('RestingECG',new_df['RestingECG'].unique())
print('MaxHR',new_df['MaxHR'].unique())
print('ExerciseAngina',new_df['ExerciseAngina'].unique())
print('Oldpeak',new_df['Oldpeak'].unique())
print('ST_Slope',new_df['ST_Slope'].unique())
print('HeartDisease',new_df['HeartDisease'].unique())

Age [40 49 37 48 54 39 45 58 42 38 43 60 36 44 53 52 51 56 41 32 65 35 59 50
 47 31 46 57 55 63 66 34 33 61 29 62 28 30 74 68 72 64 69 67 73 70 77 75
 76 71]
Sex ['M' 'F']
ChestPainType ['ATA' 'NAP' 'ASY' 'TA']
RestingBP [140 160 130 138 150 120 110 136 115 100 124 113 125 145 112 132 118 170
 142 190 135 180 108 155 128 106  92 200 122  98 105 133  95  80 137 185
 165 126 152 116 144 154 134 104 139 131 141 178 146 158 123 102  96 143
 172 156 114 127 101 174  94 148 117 192 129 164]
Cholesterol [289 180 283 214 195 339 237 208 207 284 211 164 204 234 273 196 201 248
 267 223 184 288 215 209 260 468 188 518 167 224 172 186 254 306 250 177
 227 230 294 264 259 175 318 216 340 233 205 245 194 270 213 365 342 253
 277 202 297 225 246 412 265 182 218 268 163 529 100 206 238 139 263 291
 229 307 210 329 147  85 269 275 179 392 466 129 241 255 276 282 338 160
 156 272 240 393 161 228 292 388 166 247 331 341 243 279 198 249 168 603
 159 190 185 290 212 231 222 235 320 187 266 287 404 312 251 328 285 280
 192 193 308 219 257 132 226 217 303 298 256 117 295 173 315 281 309 200
 336 355 326 171 491 271 274 394 221 126 305 220 242 347 344 358 169 181
 236 203 153 316 311 252 458 384 258 349 142 197 113 261 310 232 110 123
 170 369 152 244 165 337 300 333 385 322 564 239 293 407 149 199 417 178
 319 354 330 302 313 141 327 304 286 360 262 325 299 409 174 183 321 353
 335 278 157 176 131]
FastingBS [0 1]
RestingECG ['Normal' 'ST' 'LVH']
MaxHR [172 156  98 108 122 170 142 130 120  99 145 140 137 150 166 165 125 160
 164 138 178 112 118 127 114 154 155  87 148 100 168 184 121 153 134  96
 174 175 144  82 135 115 128 116  94 110  92 180 152 124 106 185 139 190
 146 158 132 176 119 188 162 105  90 136 167 129 102 143 103  91 126  93
 131 149 123 182 141  77 109 133 179 113 104  95  72  97 117  86  63 157
  83  60  70 163  67  78  84 111  80 107 161  69  88  73 159 151 181 186
 177 173 169 171 147  71 192 195 194 187 202]
ExerciseAngina ['N' 'Y']
Oldpeak [ 0.   1.   1.5  2.   3.   4.   0.5  2.5  5.   0.8  0.7  1.4  2.1  0.4
  0.2  1.7  2.2  0.1  1.6  1.3  0.3  1.8  2.6 -0.9  2.8 -2.6 -1.5 -0.1
  0.9  1.1  2.4 -1.  -1.1 -0.7 -0.8  3.7  1.2 -0.5 -2.   1.9  3.5  0.6
  3.1  2.3  3.4  3.6  4.2  3.2  5.6  3.8  2.9  6.2  4.4]
ST_Slope ['Up' 'Flat' 'Down']
HeartDisease [0 1]

In [5]:
df_mapping=new_df.copy()

map_Sex={'M':0, 'F':1}
map_ChestPainType={'ATA':0, 'NAP':1, 'ASY':2, 'TA':3}
map_RestingECG={'Normal':0, 'ST':1, 'LVH':2}
map_ExerciseAngina={'N':0, 'Y':1}
map_ST_Slope={'Up':0, 'Flat':1, 'Down':1}

df_mapping['Sex']=df_mapping['Sex'].map(map_Sex)
df_mapping['ChestPainType']=df_mapping['ChestPainType'].map(map_ChestPainType)
df_mapping['RestingECG']=df_mapping['RestingECG'].map(map_RestingECG)
df_mapping['ExerciseAngina']=df_mapping['ExerciseAngina'].map(map_ExerciseAngina)
df_mapping['ST_Slope']=df_mapping['ST_Slope'].map(map_ST_Slope)
df_mapping.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,0,0,140,289,0,0,172,0,0.0,0,0
1,49,1,1,160,180,0,0,156,0,1.0,1,1
2,37,0,0,130,283,0,1,98,0,0.0,0,0
3,48,1,2,138,214,0,0,108,1,1.5,1,1
4,54,0,1,150,195,0,0,122,0,0.0,0,0

In [6]:
dummied_new_df=pd.get_dummies(new_df, columns=['Sex', 'ChestPainType', 'RestingECG',
                                               'ExerciseAngina', 'ST_Slope'])
dummied_new_df

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_F,Sex_M,ChestPainType_ASY,...,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,0,1,0,...,0,0,0,1,0,1,0,0,0,1
1,49,160,180,0,156,1.0,1,1,0,0,...,1,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0.0,0,0,1,0,...,0,0,0,0,1,1,0,0,0,1
3,48,138,214,0,108,1.5,1,1,0,1,...,0,0,0,1,0,0,1,0,1,0
4,54,150,195,0,122,0.0,0,0,1,0,...,1,0,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,1.2,1,0,1,0,...,0,1,0,1,0,1,0,0,1,0
914,68,144,193,1,141,3.4,1,0,1,1,...,0,0,0,1,0,1,0,0,1,0
915,57,130,131,0,115,1.2,1,0,1,1,...,0,0,0,1,0,0,1,0,1,0
916,57,130,236,0,174,0.0,1,1,0,0,...,0,0,1,0,0,1,0,0,1,0
917,38,138,175,0,173,0.0,0,0,1,0,...,1,0,0,1,0,1,0,0,0,1

In [7]:
x=dummied_new_df.drop(['HeartDisease'],axis=1).copy()
x.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_F,Sex_M,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,1,0,1,0,0,0,1,0,1,0,0,0,1
1,49,160,180,0,156,1.0,1,0,0,0,1,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0.0,0,1,0,1,0,0,0,0,1,1,0,0,0,1
3,48,138,214,0,108,1.5,1,0,1,0,0,0,0,1,0,0,1,0,1,0
4,54,150,195,0,122,0.0,0,1,0,0,1,0,0,1,0,1,0,0,0,1

In [8]:
y=df['HeartDisease'].copy()
y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=4)

In [13]:
clf1 = DecisionTreeClassifier(random_state=4)
param_grid1 = [{'max_depth': [5,10,15],
                'max_leaf_nodes':[10,15,20],
                'criterion': ['gini']}]
cross_val=KFold(n_splits=3,shuffle=True,random_state=4)

In [10]:
clf1 = DecisionTreeClassifier(random_state=4)
param_grid1 = [{'max_depth': [5],
                'max_leaf_nodes':[10],
                'criterion': ['gini']}]
cross_val=KFold(n_splits=3,shuffle=True,random_state=4)

In [12]:
# using gridsearch for hyper-parameter tuning
specificity = make_scorer(recall_score, pos_label=0)
gridS_model = GridSearchCV(estimator=clf1,
                                param_grid=param_grid1,
                                scoring='accuracy',
                                n_jobs=-1,
                                cv=cross_val,
                                verbose=0,
                                refit=True)

cv_outer = KFold(n_splits=3, shuffle=True, random_state=4)

train_scores = cross_val_score(gridS_model, x_train, y_train, scoring='accuracy', cv=cv_outer, n_jobs=-1)
train_scores_f1 = cross_val_score(gridS_model, x_train, y_train, scoring='f1', cv=cv_outer, n_jobs=-1)
train_scores_precision = cross_val_score(gridS_model, x_train, y_train, scoring='precision', cv=cv_outer, n_jobs=-1)
train_scores_sen = cross_val_score(gridS_model, x_train, y_train, scoring='recall', cv=cv_outer, n_jobs=-1)
train_scores_spe = cross_val_score(gridS_model, x_train, y_train, scoring=specificity, cv=cv_outer, n_jobs=-1)

test_scores = cross_val_score(gridS_model, x_test, y_test, scoring='accuracy', cv=cv_outer, n_jobs=-1)
test_scores_f1 = cross_val_score(gridS_model, x_test, y_test, scoring='f1', cv=cv_outer, n_jobs=-1)
test_scores_precision = cross_val_score(gridS_model, x_test, y_test, scoring='precision', cv=cv_outer, n_jobs=-1)
test_scores_sen = cross_val_score(gridS_model, x_test, y_test, scoring='recall', cv=cv_outer, n_jobs=-1)
test_scores_spe = cross_val_score(gridS_model, x_train, y_train, scoring=specificity, cv=cv_outer, n_jobs=-1)

#peforming gridsearch & save each models training result
print('train ACC:',round((np.mean(train_scores))*100,2),'+/-',round((np.std(train_scores))*100,2))
print('train fls:',round((np.mean(train_scores_f1))*100,2),'+/-',round((np.std(train_scores_f1))*100,2))
print('train precision:',round((np.mean(train_scores_precision))*100,2),'+/-',round((np.std(train_scores_precision))*100,2))
print('train sen:',round((np.mean(train_scores_sen))*100,2),'+/-',round((np.std(train_scores_sen))*100,2))
print('train spe:',round((np.mean(train_scores_spe))*100,2),'+/-',round((np.std(train_scores_spe))*100,2))
print('+----------------------------------------+')

print('test ACC:',round((np.mean(test_scores))*100,2),'+/-',round((np.std(test_scores))*100,2))
print('test fls:',round((np.mean(test_scores_f1))*100,2),'+/-',round((np.std(test_scores_f1))*100,2))
print('test precision:',round((np.mean(test_scores_precision))*100,2),'+/-',round((np.std(test_scores_precision))*100,2))
print('test sen:',round((np.mean(test_scores_sen))*100,2),'+/-',round((np.std(test_scores_sen))*100,2))
print('test sen:',round((np.mean(test_scores_spe))*100,2),'+/-',round((np.std(test_scores_spe))*100,2))

train ACC: 83.1 +/- 3.04
train fls: 85.56 +/- 3.38
train precision: 81.32 +/- 4.28
train sen: 90.4 +/- 3.8
train spe: 73.86 +/- 3.93
+----------------------------------------+
test ACC: 83.17 +/- 1.9
test fls: 83.62 +/- 1.72
test precision: 85.11 +/- 3.32
test sen: 82.38 +/- 3.48
test sen: 73.86 +/- 3.93